# Login Details
username:             example  
password:             password

# User follower lists to search for targets
target_users_list:
  - username1
  - username2
  - username3

# Hashtags to search for targets
tag_list:
  - hashtag
  - taghash
  - hathsah

# Optional Stuff: 
#   This is all currently just the default values and can be omitted

# Limit details
max_hour_follows:     10
day_activity_hours:   16
likes_per_follow:     3
unfollows_per_follow: 1.1
explores_per_follow:  10

# Max users the bot will concurrently follow
max_followed:         100

# Sleep times per request and on spam detection (again optional)
mean_wait_time:       1
spam_wait_time:       43200

# Decay rate of day; eg data halves in 'importance' every 7 days here
data_half_life:       7

