# max_hour_likes and max_hour_follows likes/follows per hour (sliding window)
# likes_per_user media likes for each targetted user
# wait on average mean_wait_time seconds between API queries
# concurrently follow up to max_followed users
# unfollow oldest followed users to maintain this number
# verbosity:
#   0: nothing
#   1: error messages, periodic likes/follows per hour
#   2: requests send
#   3: sleep time
username:         example # should match directory file is in
password:         password
max_hour_likes:   40
max_hour_follows: 20
likes_per_user:   3
mean_wait_time:   1
max_followed:     100
verbosity:        1
tag_list:
  - hashtag
  - taghash
  - hathsah
